version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
  todo-app:
    image: ${APP_NAME}:${VERSION}
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:      
      - ./logs:/app/todo-app/logs:ro
